# Dataframe from excel or numpy matrix

In [1]:
# import excel file OR
import pandas as pd
data_frame= pd.read_excel("Grades.xlsx")

In [2]:
#convert numpy into dataframe
import numpy as np
import pandas as pd

my_array = np.array([[11,22,33],[44,55,66]])

df = pd.DataFrame(my_array, columns = ['Column_A','Column_B','Column_C'])

In [ ]:
# convert sklearn dataset into pandas datafram
from sklearn.datasets import load_breast_cancer
dataset = load_breast_cancer(as_frame=True)
#Converting into dataframe
df = pd.DataFrame(data=dataset.data, columns=dataset.feature_names)
df.head()

# Preparing data
Delete columns if not necessary with goals, if lot of NAs, if non-comparable values.

On hot encode when names of countries for eg

Keep 1 column when many of the same info

Normalize quantities

### Inspecting data

In [9]:
data_frame.describe()# gives statistical vue of data

Unnamed: 0     Grades    Credits
count         0.0  18.000000  18.000000
mean          NaN  67.444444   5.333333
std           NaN  24.886146   0.766965
min           NaN  22.000000   4.000000
25%           NaN  47.250000   5.000000
50%           NaN  73.500000   5.500000
75%           NaN  90.000000   6.000000
max           NaN  99.000000   6.000000

In [7]:
data_frame.head(5)#first 5 rows of the data

Unnamed: 0      Name Class     Lectures  Grades  Credits Retake
0         NaN  Benjamin     A  Mathematics      90        6     No
1         NaN  Benjamin     A    Chemistry      54        6     No
2         NaN  Benjamin     A      Physics      77        6     No
3         NaN  Benjamin     A      History      22        5    Yes
4         NaN  Benjamin     A    Geography      25        5    Yes

In [8]:
data_frame.tail(5)#last five rows

Unnamed: 0  Name Class   Lectures  Grades  Credits Retake
13         NaN  Toni     C  Chemistry      44        6    Yes
14         NaN  Toni     C    Physics      56        6     No
15         NaN  Toni     C    History      77        5     No
16         NaN  Toni     C  Geography      35        5    Yes
17         NaN  Toni     C     German      99        4     No

In [10]:
data_frame.shape#nb rows and columns

(18, 7)

In [11]:
data_frame.info()#index, datatype, memory info

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Unnamed: 0  0 non-null      float64
 1   Name        18 non-null     object 
 2   Class       18 non-null     object 
 3   Lectures    18 non-null     object 
 4   Grades      18 non-null     int64  
 5   Credits     18 non-null     int64  
 6   Retake      18 non-null     object 
dtypes: float64(1), int64(2), object(4)
memory usage: 1.1+ KB


In [12]:
# see unique values and their counts
data_frame["Grades"].value_counts(dropna=False)#.sort_index(ascending=True)#to see unique values and their counts

90    6
70    2
77    2
35    1
22    1
44    1
99    1
54    1
56    1
25    1
45    1
Name: Grades, dtype: int64

In [13]:
data_frame.mean()#gives means of each columns when possible

Unnamed: 0          NaN
Grades        67.444444
Credits        5.333333
dtype: float64

In [14]:
data_frame.corr()# gives correlations between columns in a data frame

Unnamed: 0    Grades   Credits
Unnamed: 0         NaN       NaN       NaN
Grades             NaN  1.000000 -0.008218
Credits            NaN -0.008218  1.000000

In [15]:
data_frame.count()# returns the number of non-null values in each column

Unnamed: 0     0
Name          18
Class         18
Lectures      18
Grades        18
Credits       18
Retake        18
dtype: int64

In [18]:
#highest value of each column
data_frame.max()# also works for min(), median(), std()

Unnamed: 0        NaN
Name             Toni
Class               C
Lectures      Physics
Grades             99
Credits             6
Retake            Yes
dtype: object

### Filtering of data

In [20]:
#Select a column:
data_frame["Grades"].head()

0    90
1    54
2    77
3    22
4    25
Name: Grades, dtype: int64

In [19]:
#Return series of few columns
data_frame[["Grades", "Credits"]].head()

Grades  Credits
0      90        6
1      54        6
2      77        6
3      22        5
4      25        5

In [5]:
#Select by columns' specific value
G= data_frame.loc[(data_frame["Name"]=="Benjamin"), ["Lectures", "Grades", "Credits", "Retake"]]
G #Results only for Benjamin

Lectures  Grades  Credits Retake
0  Mathematics      90        6     No
1    Chemistry      54        6     No
2      Physics      77        6     No
3      History      22        5    Yes
4    Geography      25        5    Yes
5       German      70        4     No

In [6]:
data_frame.loc[0].at["Grades"]# first item of "Grades" in the file. Use iat for indexes.

90

In [23]:
# First row
data_frame.iloc[0,:]# or: data_frame.loc[0]

Unnamed: 0            NaN
Name             Benjamin
Class                   A
Lectures      Mathematics
Grades                 90
Credits                 6
Retake                 No
Name: 0, dtype: object

In [24]:
#first element of the first column
data_frame.iloc[0,0]

nan

In [25]:
#Boolean filtering AND
data_frame[data_frame["Grades"]>50 & (data_frame["Name"] == "Benjamin")].head()

Unnamed: 0      Name Class     Lectures  Grades  Credits Retake
0         NaN  Benjamin     A  Mathematics      90        6     No
1         NaN  Benjamin     A    Chemistry      54        6     No
2         NaN  Benjamin     A      Physics      77        6     No
3         NaN  Benjamin     A      History      22        5    Yes
4         NaN  Benjamin     A    Geography      25        5    Yes

In [26]:
#Boolean filtering OR
data_frame[data_frame["Grades"]>50 | (data_frame["Name"] == "Benjamin")].head()

Unnamed: 0      Name Class     Lectures  Grades  Credits Retake
0         NaN  Benjamin     A  Mathematics      90        6     No
1         NaN  Benjamin     A    Chemistry      54        6     No
2         NaN  Benjamin     A      Physics      77        6     No
3         NaN  Benjamin     A      History      22        5    Yes
4         NaN  Benjamin     A    Geography      25        5    Yes

#### Sort and Groupby

In [28]:
#Sorting column values in ascending order
#Boolean filtering
data_frame.sort_values("Grades").head()# for descending order add argument "ascending=False"

Unnamed: 0      Name Class   Lectures  Grades  Credits Retake
3          NaN  Benjamin     A    History      22        5    Yes
4          NaN  Benjamin     A  Geography      25        5    Yes
16         NaN      Toni     C  Geography      35        5    Yes
13         NaN      Toni     C  Chemistry      44        6    Yes
9          NaN     Safia     B    History      45        5     No

In [29]:
data_frame.sort_values(["Grades", "Credits"], ascending= [True, False]).head()

Unnamed: 0      Name Class   Lectures  Grades  Credits Retake
3          NaN  Benjamin     A    History      22        5    Yes
4          NaN  Benjamin     A  Geography      25        5    Yes
16         NaN      Toni     C  Geography      35        5    Yes
13         NaN      Toni     C  Chemistry      44        6    Yes
9          NaN     Safia     B    History      45        5     No

In [30]:
# Group by for values from one column
data_frame.groupby("Name", as_index=False).mean() #mean of grades and credits for each student

Name  Unnamed: 0     Grades   Credits
0  Benjamin         NaN  56.333333  5.333333
1     Safia         NaN  82.500000  5.333333
2      Toni         NaN  63.500000  5.333333

In [31]:
#groupby object for values from multiple columns
data_frame.groupby(["Name","Credits"], as_index=False).mean().head()

Name  Credits  Unnamed: 0     Grades
0  Benjamin        4         NaN  70.000000
1  Benjamin        5         NaN  23.500000
2  Benjamin        6         NaN  73.666667
3     Safia        4         NaN  90.000000
4     Safia        5         NaN  67.500000

#### Join/combine

In [32]:
#Creating a dataframe
classes= pd.Series(["Mathematics", "Chemistry", "Physics", "History", "Geography", "German"])
classes2= pd.Series(["Mathematics", "Chemistry", "Physics", "History", "Geography", "German"])

grades= pd.Series([90,54,77,22,25])

In [33]:
#add the rows in df1 to the end of df2
classes.append(grades)

0    Mathematics
1      Chemistry
2        Physics
3        History
4      Geography
5         German
0             90
1             54
2             77
3             22
4             25
dtype: object

In [34]:
#add the rows in df1 to the end of df2
from pandas import concat
concat([classes, grades],axis=0) 

0    Mathematics
1      Chemistry
2        Physics
3        History
4      Geography
5         German
0             90
1             54
2             77
3             22
4             25
dtype: object

In [35]:
#add the columns in df1 next to df2
from pandas import concat
concat([classes, grades],axis=1) 

0     1
0  Mathematics  90.0
1    Chemistry  54.0
2      Physics  77.0
3      History  22.0
4    Geography  25.0
5       German   NaN

### Creation of new column

In [36]:
# Reduction operation
import numpy as np

credits = data_frame[["Credits","Grades"]]

credits.apply(np.sum)

Credits      96
Grades     1214
dtype: int64

In [37]:
# Creation of a column
data_frame["Name"] = data_frame["Grades"].apply(lambda val: "Benjamin" if val < 45 else "Lise")

# Normalize

In [39]:
# Normalize results with scikit learn
import sklearn
from sklearn.preprocessing import StandardScaler
scaled_features = StandardScaler().fit_transform(data_frame["Grades"].values.reshape(-1, 1))

# One hot encoding of y

In [40]:
# creation of one hot, dummies
dummies=pd.get_dummies(data_frame["Name"], prefix="Name")
print(dummies.head())

   Name_Benjamin  Name_Lise
0              0          1
1              0          1
2              0          1
3              1          0
4              1          0


# Numpy

In [42]:
# convert dataframe to numpy
matrix_np=data_frame.to_numpy()
type(matrix_np)

numpy.ndarray

In [ ]:
#Convert numpy array back to dataframe
y_pred2 = pd.DataFrame(y_pred, columns = ['Predictions'])

Creation of matrices

In [43]:
np.array([[1,2,3],[4,5,6]], dtype=np.uint64)

array([[1, 2, 3],
       [4, 5, 6]], dtype=uint64)

In [44]:
np.arange(1,5)# ou pn.arange(1,3,0.5): start, stop, step

array([1, 2, 3, 4])

In [45]:
np.linspace(1,10)#start, stop, num (nombre de valeurs souhaitées)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [46]:
print(np.zeros((2,3), dtype=int))
print(np.ones((2,3), dtype=int))
print(np.full((2,3),-1, dtype=int))

[[0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]]
[[-1 -1 -1]
 [-1 -1 -1]]


In [47]:
# Distribution uniforme:
c=np.random.rand(2,3)
print(c)

[[0.92928397 0.00521705 0.66550568]
 [0.8592787  0.68521246 0.0077527 ]]


Reshape and transpose

In [48]:
a= np.zeros(6, dtype=int)
b=a.reshape(2,3)
print(a)
print(b)

[0 0 0 0 0 0]
[[0 0 0]
 [0 0 0]]


In [49]:
c.T

array([[0.92928397, 0.8592787 ],
       [0.00521705, 0.68521246],
       [0.66550568, 0.0077527 ]])

Indexing and slicing

In [51]:
# Converting the matrix in the other way around
c[::-1]

array([[0.8592787 , 0.68521246, 0.0077527 ],
       [0.92928397, 0.00521705, 0.66550568]])

In [52]:
h= np.array([[1,2,3],[4,5,6]])
i=np.ravel(h)# make vector
print(h)
print(i)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


vstack, hstack

In [53]:
np.vstack((c,h)) #stick vertically (arrays have to have same dimensions)

array([[9.29283967e-01, 5.21705121e-03, 6.65505681e-01],
       [8.59278699e-01, 6.85212456e-01, 7.75270180e-03],
       [1.00000000e+00, 2.00000000e+00, 3.00000000e+00],
       [4.00000000e+00, 5.00000000e+00, 6.00000000e+00]])

In [54]:
np.hstack((c,h)) #stick vertically (arrays have to have same dimensions)

array([[9.29283967e-01, 5.21705121e-03, 6.65505681e-01, 1.00000000e+00,
        2.00000000e+00, 3.00000000e+00],
       [8.59278699e-01, 6.85212456e-01, 7.75270180e-03, 4.00000000e+00,
        5.00000000e+00, 6.00000000e+00]])

Split

In [55]:
np.split(h,3,axis=1)

[array([[1],
        [4]]),
 array([[2],
        [5]]),
 array([[3],
        [6]])]